# @Author: Argann BONNEAU <AlphaDreams>
# @Date:   28-07-2017 10:03
# @Email:  argann.b@hotmail.fr
# @Project: Buried Sky
# @Filename: docker-compose.yml
# @Last modified by:   AlphaDreams
# @Last modified time: 28-07-2017 10:51

version: "3.2"
services:
    server:
        build: .
        ports:
            - "5000:5000"
        restart: on-failure
    database:
        image: mysql
        environment:
            MYSQL_DATABASE: bs_db
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: bs_user
            MYSQL_PASSWORD: bs_pwd
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: phpmyadmin
        environment:
            - PMA_ARBITRARY=1
        restart: always
        ports:
            - 8080:80
        volumes:
            - /sessions
