export enum MatchState {
    
    WAITING_FOR_PLAYERS = 'WAITING_FOR_PLAYERS',
    WAIT_PLAYER_1 = 'WAIT_PLAYER_1',
    WAIT_PLAYER_2 = 'WAIT_PLAYER_2',
    RESOLVE_PLAYER_1 = 'RESOLVE_PLAYER_1',
    RESOLVE_PLAYER_2 = 'RESOLVE_PLAYER_2',
    ENDED = 'ENDED',
    CANCELLED = 'CANCELLED'

}